### ISSUE TITLE
Shell Command should be called ShellCommand in Package control.

### ISSUE THREAD

**Issue by randy3k** [markbirbeck/sublime-text-gitmode#9]
Perhaps I should submit this issue at ShellCommand repo, but I encountered it when I tried to install Git Mode.

When Shell Command is installed via PC. It is named "Shell Command", and `import ShellCommand` will throw an error.
To make Git Mode working with ShellCommand installed via PC. "Shell Command" should be called ShellCommand.

**Comment by bluebirch** [comment]
Indeed.

**Comment by markbirbeck** [comment]
Thanks @randy3k. I had renamed the directory during testing...sorry about that!

I've submitted a request to rename the package so hopefully that will fix it.

**Comment by markbirbeck** [comment]
Hopefully this is sorted with the change in package control, but let me know if anything else comes up.

Thanks again.
